export const FETCH_APPOINTMENTS_REQUEST = 'redux/appointment/FETCH_APPOINTMENTS_REQUEST';
export const FETCH_APPOINTMENTS_SUCCESS = 'redux/appointment/FETCH_APPOINTMENTS_SUCCESS';
export const FETCH_APPOINTMENTS_FAILURE = 'redux/appointment/FETCH_APPOINTMENTS_FAILURE';
