export const UPDATE_ORDER_TO_TRANSACTION_REQUEST = '/redux/kasir/updateOrder/UPDATE_ORDER_TO_TRANSACTION_REQUEST';
export const UPDATE_ORDER_TO_TRANSACTION_SUCCESS = '/redux/kasir/updateOrder/UPDATE_ORDER_TO_TRANSACTION_SUCCESS';
export const UPDATE_ORDER_TO_TRANSACTION_FAILURE = '/redux/kasir/updateOrder/UPDATE_ORDER_TO_TRANSACTION_FAILURE';
