export const CHANGE_PASSWORD_REQUEST = 'redux/change/CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'redux/change/CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'redux/change/CHANGE_PASSWORD_FAILURE';
