export const FETCH_PROFILE_REQUEST = 'redux/profile/FETCH_PROFILE_REQUEST';
export const FETCH_PROFILE_SUCCESS = 'redux/profile/FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAILURE = 'redux/profile/FETCH_PROFILE_FAILURE';

export const UPDATE_PROFILE_REQUEST = 'redux/profile/UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'redux/profile/UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'redux/profile/UPDATE_PROFILE_FAILURE';