export const SUBMIT_RESPONSES_REQUEST = 'SUBMIT_RESPONSES_REQUEST';
export const SUBMIT_RESPONSES_SUCCESS = 'SUBMIT_RESPONSES_SUCCESS';
export const SUBMIT_RESPONSES_FAILURE = 'SUBMIT_RESPONSES_FAILURE';
export const FETCH_RESPONSES_REQUEST = 'FETCH_RESPONSES_REQUEST';
export const FETCH_RESPONSES_SUCCESS = 'FETCH_RESPONSES_SUCCESS';
export const FETCH_RESPONSES_FAILURE = 'FETCH_RESPONSES_FAILURE';
