export const SUBMIT_RESPONSES_REQUEST = 'SUBMIT_RESPONSES_REQUEST';
export const SUBMIT_RESPONSES_SUCCESS = 'SUBMIT_RESPONSES_SUCCESS';
export const SUBMIT_RESPONSES_FAILURE = 'SUBMIT_RESPONSES_FAILURE';
