export const ACTIVATE_ACCOUNT_REQUEST = 'redux/activated/ACTIVATE_ACCOUNT_REQUEST';
export const ACTIVATE_ACCOUNT_SUCCESS = 'redux/activated/ACTIVATE_ACCOUNT_SUCCESS';
export const ACTIVATE_ACCOUNT_FAILURE = 'redux/activated/ACTIVATE_ACCOUNT_FAILURE';
