export const DELETE_PENDAFTAR_REQUEST = 'DELETE_PENDAFTAR_REQUEST';
export const DELETE_PENDAFTAR_SUCCESS = 'DELETE_PENDAFTAR_SUCCESS';
export const DELETE_PENDAFTAR_FAILURE = 'DELETE_PENDAFTAR_FAILURE';
