export const FETCH_DETAIL_TRANSACTIONS_REQUEST = '/redux/kasir/indexOrderDetail/FETCH_DETAIL_TRANSACTIONS_REQUEST';
export const FETCH_DETAIL_TRANSACTIONS_SUCCESS = '/redux/kasir/indexOrderDetail/FETCH_DETAIL_TRANSACTIONS_SUCCESS';
export const FETCH_DETAIL_TRANSACTIONS_FAILURE = '/redux/kasir/indexOrderDetail/FETCH_DETAIL_TRANSACTIONS_FAILURE';
