export const GET_ORDER_INFORMATION_REQUEST = 'redux/doctor/orderInfo/GET_ORDER_INFORMATION_REQUEST';
export const GET_ORDER_INFORMATION_SUCCESS = 'redux/doctor/orderInfo/GET_ORDER_INFORMATION_SUCCESS';
export const GET_ORDER_INFORMATION_FAILURE = 'redux/doctor/orderInfo/GET_ORDER_INFORMATION_FAILURE';
