export const FETCH_NOTIFIKASI_REQUEST = 'FETCH_NOTIFIKASI_REQUEST';
export const FETCH_NOTIFIKASI_SUCCESS = 'FETCH_NOTIFIKASI_SUCCESS';
export const FETCH_NOTIFIKASI_FAILURE = 'FETCH_NOTIFIKASI_FAILURE';

export const UPDATE_STATUS_REQUEST = 'UPDATE_STATUS_REQUEST';
export const UPDATE_STATUS_SUCCESS = 'UPDATE_STATUS_SUCCESS';
export const UPDATE_STATUS_FAILURE = 'UPDATE_STATUS_FAILURE';
