export const CREATE_PENDAFTAR_REQUEST = 'CREATE_PENDAFTAR_REQUEST';
export const CREATE_PENDAFTAR_SUCCESS = 'CREATE_PENDAFTAR_SUCCESS';
export const CREATE_PENDAFTAR_FAILURE = 'CREATE_PENDAFTAR_FAILURE';
