export const FORGOT_PASSWORD_REQUEST = 'redux/forgot/FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'redux/forgot/FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'redux/forgot/FORGOT_PASSWORD_FAILURE';
